### ISSUE TITLE
live session error

### ISSUE THREAD

**Issue by dgiunchi** [kkuette/TradzQAI#19]
I have this problem when run with the live session:

Traceback (most recent call last):
  File "run.py", line 42, in <module>
    product_id=product_id)
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\core\session\live.py", line 119, in initApi
    self.initEnv()
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\core\session\live.py", line 124, in initEnv
    logger=self.logger, saver=self.saver, dataloader=self.dl, api=self.api)
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\core\environnement\live_env.py", line 99, in __init__
    self.dl.loadHistorical()
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\core\environnement\base\dataloader.py", line 245, in loadHistorical
    self.ticks = tick.join(self.indics.build_indicators(tick['Price']))
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\tools\indicators\build_indicators.py", line 76, in build_indicators
    indicators[idx[1]] = idx[0](data, idx[2][0], idx[2][1])
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\tools\indicators\moving_average_convergence_divergence.py", line 12, in moving_average_convergence_divergence
    check_for_period_error(data, long_period)
  File "C:\Users\dannox\Google Drive\stockOptionsTrading\TradzQAI\TradzQAI\tools\indicators\catch_errors.py", line 14, in check_for_period_error
    raise Exception("Error: data_len < period")
Exception: Error: data_len < period
Error: messages missing (4948236479 - 4948236523). Re-initializing  book at sequence.

**Comment by kkuette** [comment]
Hi, did you change something from the original code ?
