### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [kkuette/TradzQAI#21]
python run.py

Traceback (most recent call last):
  File "run.py", line 30, in <module>
    from TradzQAI import Local_session as Session
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/__init__.py", line 1, in <module>
    from .core import Local_session
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/core/__init__.py", line 1, in <module>
    from .environnement import Local_env
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/core/environnement/__init__.py", line 1, in <module>
    from .local_env import Local_env
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/core/environnement/local_env.py", line 1, in <module>
    from TradzQAI.tools import act_processing
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/tools/__init__.py", line 5, in <module>
    from .utils import *
  File "/home/desktop/Downloads/TradzQAI-master/TradzQAI/tools/utils.py", line 22
SyntaxError: Non-ASCII character '\xe2' in file /home/desktop/Downloads/TradzQAI-master/TradzQAI/tools/utils.py on line 22, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by AlconDivino** [comment]
I get the same Error when running with python

when running with python3 i get 

Can not find Murmur3 hashing installed. Switching to SHA256 as the default hash. Refer to https://github.com/seperman/deepdiff#murmur3 for more info.
Warning : the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Traceback (most recent call last):
  File "run.py", line 38, in <module>
    session.loadSession()
  File "/home/alcon/Desktop/TradzQAI/TradzQAI/TradzQAI/core/session/local.py", line 72, in loadSession
    self.initEnv()
  File "/home/alcon/Desktop/TradzQAI/TradzQAI/TradzQAI/core/session/local.py", line 103, in initEnv
    logger=self.logger, saver=self.saver, dataloader=self.dl)
  File "/home/alcon/Desktop/TradzQAI/TradzQAI/TradzQAI/core/environnement/local_env.py", line 84, in __init__
    self.dl.loadFile()
  File "/home/alcon/Desktop/TradzQAI/TradzQAI/TradzQAI/core/environnement/base/dataloader.py", line 170, in loadFile
    tmp_data, tmp_raw, tmp_time = self.getStockDataVec(self.files[self.files_index])
  File "/home/alcon/Desktop/TradzQAI/TradzQAI/TradzQAI/core/environnement/base/dataloader.py", line 148, in getStockDataVec
    df.columns = names
UnboundLocalError: local variable 'names' referenced before assignment

Nothing changed just installed dependencies and ra run.py

**Comment by AlconDivino** [comment]
When running python3 and a right formatted dataset it runs just fine now!

**Comment by eragamreddyvenkatasreekanthreddy** [comment]
traceback (most recent call last): file "run.py" line 2 in  import local_session as session importerror: no module named local_session
